name: Deploy .NET App to Azure via FTP

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release

      - name: Publish the application
        run: dotnet publish --configuration Release --output ./publish

      - name: FTP Deployment to Azure
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.AZURE_FTP_SERVER }}
          username: ${{ secrets.AZURE_FTP_USERNAME }}
          password: ${{ secrets.AZURE_FTP_PASSWORD }}
          local-dir: ./publish
          server-dir: /site/wwwroot
