name: Deploy .NET App to Azure via FTP

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release

      - name: Publish the application
        run: dotnet publish --configuration Release --output ./publish

      - name: Create app_offline.htm
        run: |
          mkdir -p offline
          echo '<html><head><title>Site Offline</title></head><body><h1>Site is offline for maintenance.</h1></body></html>' > offline/app_offline.htm

      - name: Check and install lftp
        run: |
          echo "Checking if lftp is installed..."
          if ! command -v lftp &> /dev/null; then
            echo "lftp not found, installing..."
            sudo apt-get update && sudo apt-get install -y lftp
          else
            echo "✅ lftp is already installed"
            lftp --version
          fi

      - name: Upload app_offline.htm via lftp
        env:
          AZURE_FTP_SERVER: ${{ secrets.AZURE_FTP_SERVER }}
          AZURE_FTP_USERNAME: ${{ secrets.AZURE_FTP_USERNAME }}
          AZURE_FTP_PASSWORD: ${{ secrets.AZURE_FTP_PASSWORD }}
        run: |
          echo "Uploading app_offline.htm to put site in maintenance mode..."
          lftp -c "
          set ftp:ssl-allow no;
          set file:use-fallocate no;
          set ftp:use-site-chmod no;
          set ftp:use-site-utime no;
          open -u $AZURE_FTP_USERNAME,$AZURE_FTP_PASSWORD $AZURE_FTP_SERVER;
          cd /site/wwwroot;
          put ./offline/app_offline.htm;
          quit
          "

      - name: Wait for app offline to take effect
        run: |
          echo "Waiting 10 seconds for app_offline.htm to stop the application..."
          sleep 10

      - name: Upload application files via lftp
        env:
          AZURE_FTP_SERVER: ${{ secrets.AZURE_FTP_SERVER }}
          AZURE_FTP_USERNAME: ${{ secrets.AZURE_FTP_USERNAME }}
          AZURE_FTP_PASSWORD: ${{ secrets.AZURE_FTP_PASSWORD }}
        run: |
          echo "Uploading application files to FTP server (preserving configs)..."
          lftp -c "
          set ftp:ssl-allow no;
          set file:use-fallocate no;
          set ftp:use-site-chmod no;
          set ftp:use-site-utime no;
          set net:max-retries 2;
          open -u $AZURE_FTP_USERNAME,$AZURE_FTP_PASSWORD $AZURE_FTP_SERVER;
          cd /site/wwwroot;
          mirror -R --no-perms --exclude appsettings.json --exclude web.config --exclude appsettings.*.json ./publish/ . 2>/dev/null || mirror -R --no-perms --exclude appsettings.json --exclude web.config ./publish/ .;
          quit
          "
          echo "✅ All files uploaded and replaced successfully!"

      - name: Remove app_offline.htm via lftp
        env:
          AZURE_FTP_SERVER: ${{ secrets.AZURE_FTP_SERVER }}
          AZURE_FTP_USERNAME: ${{ secrets.AZURE_FTP_USERNAME }}
          AZURE_FTP_PASSWORD: ${{ secrets.AZURE_FTP_PASSWORD }}
        run: |
          echo "Removing app_offline.htm to bring site back online..."
          lftp -c "
          set ftp:ssl-allow no;
          set file:use-fallocate no;
          set ftp:use-site-chmod no;
          set ftp:use-site-utime no;
          open -u $AZURE_FTP_USERNAME,$AZURE_FTP_PASSWORD $AZURE_FTP_SERVER;
          cd /site/wwwroot;
          rm -f app_offline.htm;
          quit
          " || echo "Warning: Could not remove app_offline.htm, continuing..."
          echo "✅ Deployment complete - site should be back online!"
